### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by BrentNewland** [rothkj1022/phppickem#10]
These are the files with modifications necessary to install PHP Pick Em. Four files total. The SQL file didn't have the e-mail templates formatted properly (escaping a character requires double quotes around that part of the query). Miscellaneous errors in other files.

Install/Index.php: 
http://pastebin.com/u8cBCujp

Includes/application_top.php:
http://pastebin.com/cBNUtd5V

Includes/header_form.php:
```php
<?php
header('Content-Type:text/html; charset=utf-8');
header('X-UA-Compatible:IE=Edge,chrome=1'); //IE8 respects this but not the meta tag when under Local Intranet
?>
<!DOCTYPE html>
<html xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Installer - PHP Pick 'Em</title>
	<link rel="stylesheet" type="text/css" media="all" href="../css/all.css" />
	<link rel="stylesheet" type="text/css" media="all" href="../css/bootstrap.min.css" />
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
	<style type="text/css">
	body {
		background-color: #777;
		color: #333;
		font-family: "Titillium Web",sans-serif;
		font-size: 1.8em;
	}
	</style>
</head>

<body>
	<div class="container">
		<header id="header" class="row">
			<div id="top-nav" class="col-sm-12">
				<div class="navbar navbar-default" role="navigation">
					<img src="logo.gif" align="right" />
				</div>
			</div>
		</header>
	<div id="pageContent">
```

Install/phppickem2.0.1.sql:
http://pastebin.com/d0BENM2e

**Comment by BrentNewland** [comment]
I'll post the updated SQL file with the 2015 schedule tomorrow.

**Comment by BrentNewland** [comment]
Still struggling with the SQL, got it almost finished. Would download the one from the forums, but there's no registration and I was banned last year for pointing out some encrypted code.

More fixes:

In includes/header.php, find:
`
`

Replace with:
`<li><a href="teams.php">Teams</a></li>
<li><a href="schedules.php">Schedules</a></li>`

In includes/application_top.php, delete:

`if ($_SESSION['loggedInUser'] === 'admin' && $_SESSION['logged'] === 'yes') {
	//$isAdmin = 1;
} else {
	//$isAdmin = 0;`

And delete the final } at the end of application_top.php.

Also in application_top.php, after:

`$adminUser = $login->get_user('admin');`

add

`if($user->userID == $adminUser->userID) {$user->is_admin = 1;} else {$user->is_admin = 0;}`

**Comment by BrentNewland** [comment]
Here's the 2015 SQL file: http://pastebin.com/Pand0HSZ

**Comment by BrentNewland** [comment]
Also, whoever runs that phppickem.ORG site can go screw themselves. Banned me from their forum for asking why their install/index.php was encoded last year. No registration. No viewing replies to a post unless logged in. Completely steals the phppickem.com homepage with only minor changes.

You know, you could send their host a DMCA takedown for copying your site.

**Comment by rothkj1022** [comment]
Thank you for reporting these issues and your solutions.  Many of these have been addressed in the latest commit.
