### ISSUE TITLE
Washington Redskins missing on 

### ISSUE THREAD

**Issue by aharonhannan** [rothkj1022/phppickem#12]
Between the 2014 and 2015 code, the abbreviation for the Washington Redskins has changed from WAS to WSH. As a result, any pick involving Redskins will not display in the Entry Form. The fix for this is simple; edit the nflp_teams table by changing the teamID column from WAS to WSH.

**Comment by hollywood-canuck** [comment]
Thanks, was driving me nuts. Don't forget to also change the logo name for the gif and svg to WSH.

**Comment by rothkj1022** [comment]
This has been fixed, although not in the same way as suggested.  As the team code change was a mistake due to updating the schedule table for 2015, I chose to set the team code back to WAS in the schedule table.  Thank you for reporting this issue!
