### ISSUE TITLE
Password Reset Not working

### ISSUE THREAD

**Issue by hollywood-canuck** [rothkj1022/phppickem#14]
There seems to be an issue with password_reset.php. None of the display messages show up, such as success, or error and no emails are sent. Hopefully this can be fixed for the new season. It would be great if the admin page had a way to reset the passwords for users as well.

**Comment by hollywood-canuck** [comment]
Fixed it:

change
 if ($query->num_rows > 0) {
to
 if ($query->num_rows == 0) {

and change 
<p><button class="btn btn-lg btn-primary btn-block" type="submit" >Submit</button></p>

to
<p><button class="btn btn-lg btn-primary btn-block" type="submit" name="submit" value="submit">Submit</button></p>

**Comment by hollywood-canuck** [comment]
still not sure how to get/set $adminUser->email, so I hardcoded my own

**Comment by rothkj1022** [comment]
Thanks for reporting this.  This has been fixed in the latest commit.
