### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by jvdreamworker** [rothkj1022/phppickem#15]
I changed the config.php changed to try different settings, nothing seems to work. I get a 500 error misconfiguration. I am sure it is something I am doing wrong but for the life of me can't find out what.

**Comment by jvdreamworker** [comment]
Here's the error from my server error log: (xx to replace ip and port addresses)

[Sun Sep 06 18:09:48.024941 2015] [core:alert] [pid 226183] [client xx.xx.xx.xxx:xxxxx] /home/survival/public_html/cclf/pickem/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration

**Comment by rothkj1022** [comment]
It sounds like your host does not allow you to override certain settings via .htaccess.  Try commenting out all of the lines in .htaccess that start with 'php_flag', and then uncommenting them one by one (in between refreshes) to determine which one is not allowed.

**Comment by jvdreamworker** [comment]
Thanks Kevin, I had worked with them over the weekend and got it resolved. 
They are very helpful. It is installed and running.

I appreciate the help.

Sent with [inky](http://inky.com?kme=signature)

**Comment by rothkj1022** [comment]
Great, glad you were able to work it out.
