### ISSUE TITLE
Timezone Offset not working

### ISSUE THREAD

**Issue by bop17000** [rothkj1022/phppickem#16]
Hello!

I think there is a problem with the SERVER_TIMEZONE_OFFSET variable.
As I am located in Europe my offset to ET is -6 hours. Somehow the define-function does not allow me to use a negative number.
Is there any workaround?

Thank you.

**Comment by rothkj1022** [comment]
This should be fixed in v2.2.2.  Thanks!

**Comment by savagegeek** [comment]
Hello rothkj1022, I can't seem to figure out why I keep getting this error 

[Thu Aug 04 18:11:55 2016] [error] [client 192.168.3.9] PHP Fatal error:  Class 'DateTimeZone' not found in /var/www/html/phppickem-2.2.2/includes/config.php on line 28

It has to do with your dateTimeZone variables....

$dateTimeZoneCurrent = new DateTimeZone("America/New_York");
$dateTimeZoneEastern = new DateTimeZone("America/New_York");
$dateTimeCurrent = new DateTime("now", $dateTimeZoneCurrent);
$dateTimeEastern = new DateTime("now", $dateTimeZoneEastern);
$offsetCurrent = $dateTimeCurrent->getOffset();
$offsetEastern = $dateTimeEastern->getOffset();
$offsetHours = ($offsetEastern - $offsetCurrent) / 3600;
define('SERVER_TIMEZONE_OFFSET', $offsetHours);

Please advise, as I have funded you for the last few years. Thanks very much.

**Comment by rothkj1022** [comment]
Try this:
http://stackoverflow.com/questions/28568992/php-5-3-fatal-error-class-datetimezone-not-found

**Comment by savagegeek** [comment]
Thanks, I tried, but still failing... I clearly do not know what I am doing wrong here, but definitely know that your code specifically states not to change anything past a certain line :-)

// ***DO NOT EDIT ANYTHING BELOW THIS LINE***
error_reporting(E_ALL ^ E_NOTICE ^ E_STRICT);
//automatically set timezone offset (hours difference between your server's timezone and eastern time)
$date_default_timezone_set = ("America/New_York");
/*$timeZoneCurrent = @date_default_timezone_get();
 if (ini_get('date.timezone')) {
        $timeZoneCurrent = ini_get('date.timezone');
}*/
$dateTimeZoneCurrent = new \DateTimeZone("America/New_York");
$dateTimeZoneEastern = new \DateTimeZone("America/New_York");
$dateTimeCurrent = new \DateTime("now", $dateTimeZoneCurrent);
$dateTimeEastern = new \DateTime("now", $dateTimeZoneEastern);
$offsetCurrent = $dateTimeCurrent->getOffset();
$offsetEastern = $dateTimeEastern->getOffset();
$offsetHours = ($offsetEastern - $offsetCurrent) / 3600;
define('SERVER_TIMEZONE_OFFSET', $offsetHours);



[Thu Aug 04 21:29:36 2016] [error] [client 192.168.3.9] PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /var/www/html/phppickem-2.2.2/includes/config.php on line 28

[Thu Aug 04 21:29:36 2016] [error] [client 192.168.3.9] PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /var/www/html/phppickem-2.2.2/includes/config.php on line 29

[Thu Aug 04 21:29:36 2016] [error] [client 192.168.3.9] PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /var/www/html/phppickem-2.2.2/includes/config.php on line 30

[Thu Aug 04 21:29:36 2016] [error] [client 192.168.3.9] PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /var/www/html/phppickem-2.2.2/includes/config.php on line 31

[Thu Aug 04 21:29:36 2016] [error] [client 192.168.3.9] PHP Fatal error:  Class 'DateTimeZone' not found in /var/www/html/phppickem-2.2.2/includes/config.php on line 28

**Comment by rothkj1022** [comment]
What version of php are you on?

**Comment by savagegeek** [comment]
php -version
PHP 5.1.6 (cli) (built: Nov  6 2014 12:25:33) 
Copyright (c) 1997-2006 The PHP Group
Zend Engine v2.1.0, Copyright (c) 1998-2006 Zend Technologies

**Comment by rothkj1022** [comment]
There's your problem. The DateTimeZone class requires php 5.2 or higher.
I'll have to update the software requirements to reflect this.

**Comment by savagegeek** [comment]
yup. ok, That makes sense then... in the README.md....
## Minimum Requirements

* PHP version 4.3 or greater
* MySQL version 4.0 or greater with mysqli enabled
* Mcrypt module for password encryption

**Comment by rothkj1022** [comment]
README.md updated with v2.2.3
