### ISSUE TITLE
Error updating picks summary: Field 'tieBreakerPoints' doesn't have a default value

### ISSUE THREAD

**Issue by canon2k5** [rothkj1022/phppickem#17]
I didn't get this error on a simple XAMPP install.  Then moved the install to another server, Linux.

Linux Server Specs.
CentOS 6.6
PHP 5.3.3
MySQL 5.6.25-2.el6

To "fix" this and get past the error, I modified the entry_form.php and commented out an error handler.

        //update summary table
        $sql = "delete from " . DB_PREFIX . "picksummary where weekNum = " . $_POST['week'] . " and userID = " . $user->userID . ";";
        $mysqli->query($sql) or die('Error updating picks summary: ' . $mysqli->error);
        $sql = "insert into " . DB_PREFIX . "picksummary (weekNum, userID, showPicks) values (" . $_POST['week'] . ", " . $user->userID . ", " . (int)$_POST['showPicks'] . ");";
       //      $mysqli->query($sql) or die('Error updating picks summary: ' . $mysqli->error);

Now I am unable to use the feature.  The picks always display.
[X] Allow others to see my picks.

I recognize that the comment out of an error handler isn't a fix but it got me past the error and made this really fantastic app useable again.

BTW. I have donated as I think this is a great product!

**Comment by canon2k5** [comment]
I don't know if this is the solution, but doing a little more playing around with this.

     CREATE TABLE IF NOT EXISTS `nflp_picksummary` (
      `weekNum` int(11) NOT NULL DEFAULT '0',
      `userID` int(11) NOT NULL DEFAULT '0',
      `tieBreakerPoints` int(11) NOT NULL,
      `showPicks` tinyint(1) NOT NULL DEFAULT '1',
       PRIMARY KEY (`weekNum`,`userID`)
     ) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED;

I removed the    `tieBreakerPoints` int(11) NOT NULL, line since it doesn't seem to be referenced by the entry_form.php.  Maybe this will help.

**Comment by canon2k5** [comment]
Ok, maybe final comment.  I reverted everything back to include the tiebreakerPoints line, however, added something to it that was likely missing.

       `tieBreakerPoints` int(11) NOT NULL DEFAULT '0',

and everything seems to be working fine.

**Comment by rothkj1022** [comment]
I have merged in your table adjustment for people who want to turn on this feature.  Thanks!
