### ISSUE TITLE
Getting PHP errors relating to the timezone on various pages

### ISSUE THREAD

**Issue by chrisyerkes** [rothkj1022/phppickem#2]
Hi, I just installed your app using 2013 data to see how it works and I'm getting a bunch of error messages throughout the app.

On the schedules.php page, I get this:

Strict Standards: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EST/-5.0/no DST' instead in /homepages/32/d507359157/htdocs/pickem/schedules.php on line 79

on the results.php page:

Strict Standards: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EST/-5.0/no DST' instead in /homepages/32/d507359157/htdocs/pickem/results.php on line 11

on scores.php:

Strict Standards: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EST/-5.0/no DST' instead in /homepages/32/d507359157/htdocs/pickem/scores.php on line 91

on schedule_edit.php:

Strict Standards: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/New_York' for 'EST/-5.0/no DST' instead in /homepages/32/d507359157/htdocs/pickem/schedule_edit.php on line 217

I'm running PHP 5.4 on my server.

Let me know if you want access to my site to review. I can setup an admin account. Thanks.

**Comment by hollywood-canuck** [comment]
Would like to see a system wide change of time. Even if I set the offset, it doesn't change the start times of the games. Essentially anywhere there is a date/time, I would like to see it displayed with the offset, and I would like to be able to specify the timezone, so wherever it says EST, change to XXX to reflect my offset.

**Comment by rothkj1022** [comment]
Some changes were made to handling timezones in v2.2.2.  Please let me know if you have any further issues.

hollywodd-canuck: Unfortunately I do not plan on implementing your feature request.  I plan on keeping all game times listed in Eastern time as NFL.com does.
