### ISSUE TITLE
After making picks in v2.2.2 , Winner shows up in results before game even starts

### ISSUE THREAD

**Issue by savagegeek** [rothkj1022/phppickem#25]
All players show up in results a "Winner" before a game starts

Current time of server is

 date
Sat Aug  6 01:27:00 EDT 2016

Screen shot below

![image](https://cloud.githubusercontent.com/assets/20848082/17454663/59e6ec32-5b6c-11e6-8ca5-53cacb4546f5.png)

Please advise 

Thank You

**Comment by savagegeek** [comment]
BTW. I have donated as My family uses this each year... this is a great product! Thanks!

**Comment by drollette** [comment]
I submitted a pull request that fixed that.

**Comment by savagegeek** [comment]
Thanks drollette,
I see that in the pull requests, but trying to figure out what you changed.
Can you point me where to fix?

Thanks so much

**Comment by drollette** [comment]
I'm on my mobile so I'm limited right now, but you should be able to view the changes in the code by opening the pull request.

**Comment by drollette** [comment]
It is the changes to the functions file:
https://github.com/rothkj1022/phppickem/pull/22/files

**Comment by savagegeek** [comment]
Correct.
I got it.
But now still another problem... Sorry for the problems, but I figured I could help by ironing out my issues before first game day...

So after the change was made, the correct date shows up for the game instead of 0 - 0 tie. Good.

But the streak still shows up in Ties 16 for each game.... I think there is another pull request for that.

Also for Results, The Winners still show up listed

Screen shots:

![image](https://cloud.githubusercontent.com/assets/20848082/17455090/b7f27cf6-5b7b-11e6-8835-d1f7dea93c34.png)

![image](https://cloud.githubusercontent.com/assets/20848082/17455104/e706ee32-5b7b-11e6-8291-2b47b80e2ad6.png)

**Comment by drollette** [comment]
Right. That is the entry form pull request.

**Comment by savagegeek** [comment]
Hi Drollette, So I have made the changes in pull requests
https://github.com/rothkj1022/phppickem/pull/23/files
and
https://github.com/rothkj1022/phppickem/pull/22/files

but I still see results.php show up for "Winners" when the game has not played yet.

The Streak and the Record functions seems to have worked, but
the "Winners" still show up with users listed when I don't think they should.

Please advise.

**Comment by savagegeek** [comment]
Hopefully we can figure this out before first game of NFL

**Comment by savagegeek** [comment]
drollette and rothkj1022,
so as you can tell from the screen shots above, the "Winners" show up even before a game 
is played... but I  noticed in the table nflp_schedule that the homeScore and visitorScore both have "0" zero in these fields, but if I change the "0" zero to NULL with an update statement, the "Winner" goes away.... I thought the code would consider "0" as a NULL and not an actual number.
It appears that this year something is different which shows up with "0" as being an actual number for the score ... thus showing up the "Winner" with users displayed...all of them.
Am I missing something here?  NULL works for the field to keep the "Winner" from showing up until all of the games have been filled in .

Can you help explain this behavior, since this is the first year I would see this issue.
Thanks for your help.

**Comment by savagegeek** [comment]
Update: Closing out this issue, as testing with NULL values fixes this issue.

**Comment by rothkj1022** [comment]
Resolved in v2.2.3
