### ISSUE TITLE
Los Angeles Rams logo(s) missing

### ISSUE THREAD

**Issue by DonThorntonJr** [rothkj1022/phppickem#27]
but there is St. Louis Rams logo(s)

**Comment by drollette** [comment]
You need to rename each file from STL.*** to LA.*** or stl.*** yo la.***, etc...

**Comment by DonThorntonJr** [comment]
duh - they also need to be changed in the repository...

**Comment by randyr505** [comment]
I created a pull request where one of the things I fixed was the logos. If you want to fork mine it is updated as of today. 

The main feature of my fork is that I added the ability to enable tiebreakers to be used. It doesn't affect the win/loss it just helps with bragging rights each week that you won. If you gamble this works well for that also. There are options in the config to enable this, it is disabled by default.

The other option I added is to have a config value set to auto hide picks until games are locked.
