### ISSUE TITLE
**********     ATTN:   THE PROJECT HAS MOVED     **********

### ISSUE THREAD

**Issue by PHPPickEm** [rothkj1022/phppickem#3]
Hi Everyone,

The Project has a NEW Home!  It is now Located at:

http://www.phppickem.org/forums
http://forums.phppickem.org
http://www.phppickem.org/support
http://support.phppickem.org

http://www.phppickem.org

If You’re Already A Member here at GitHub or at Sourceforge, You’ll still need to Register at the new site.  Please register using Your Current Username so we’ll all know who everyone is.  Additionally, after registering a new account, we’ll transfer all of Your Statistical Data & Posts under Your Username.

We now have a custom-designed PHPPick'Em Theme, a Code Repository, a Downloads Area where everyone can download all of the versions of PHPPick'Em, a Bug Tracker, Advance Code Boxes, Custom Graphics, etc., etc.  It’s an enhanced version of Sourceforge & GitHub combined, that we feel will be unmatched by others, and should be easier to use and enjoyed by all.  This will be an asset to all involved and a benefit to everyone that will take us & the Project into the future.  Please be patient as we complete the transition to the new site
	
Best Regards, and Enjoy The New Site!

**Comment by TheRumpledOne** [comment]
There is no place on the site to register.  I am trying to install PHPPICKEM and it is not installing properly due to bugs in the files.  Where can I contact someone and get help?  Thanks.

**Comment by rothkj1022** [comment]
The project has not moved, it has been forked only.

**Comment by drollette** [comment]
Hi Kevin. I have been playing with your code for a few weeks and created a
PayPal mod to use with the pool. It utilizes an ipn to to automatically
update user accounts when they make payments. I would love to share what
I've done on the support Forum and have access to other people's work
they've shared. I cannot find a link to register for the support Forum. Any
help would be greatly appreciated! Thank you ~ Charlie

**Comment by TheRumpledOne** [comment]
I would love to have that modification.


Thanks.

Avery T. Horton, Jr. aka TheRumpledOne
