### ISSUE TITLE
Error when creating new user

### ISSUE THREAD

**Issue by guardadoe** [rothkj1022/phppickem#7]
( ! ) Deprecated: Function mysql_numrows() is deprecated in C:\wamp\www\pickem\signup.php on line 32
Call Stack
#	Time	Memory	Function	Location
1	0.0005	272688	{main}( )	..\signup.php:0

Server version: 5.6.17 - MySQL Community Server (GPL)
Protocol version: 10

Apache/2.4.9 (Win64) PHP/5.5.12

**Comment by rothkj1022** [comment]
The latest version uses mysqli and should no longer have this error.
