### ISSUE TITLE
Install Not Working

### ISSUE THREAD

**Issue by TrendyGuy** [rothkj1022/phppickem#8]
Hi,

Been trying to get your software to work with Inmotion Hosting but can't seem to get it right. At first I get a .htaccess error with php_flag, with this error I am not able to even open the install/index.php. If I remove that code from the .htaccess I can then access the install directory. I edit the includes/config.php, with all the correct information, and I am told it cannot connect to the database.

If I try to setup the database tables myself and run the software it seems to work and I create users but when logged in as an admin most the options do no show up and the software is useless.

Would anyone be able to help me get this setup? I tried creating an account on the forums but there doesn't seem to be a place to register.

**Comment by BrentNewland** [comment]
The author of the script has apparently heavily rewritten it, then stopped. Lots of bugs.

If you just want to get it installed, add the following in install/index.php after "require('../includes/config.php');":

$mysqli = new mysqli(DB_HOSTNAME, DB_USERNAME, DB_PASSWORD, DB_DATABASE);
$mysqli->set_charset('utf8');

And then find:
if (!$dbConnected)

and replace with:
if (!$mysqli)

**Comment by BrentNewland** [comment]
A few other critical fixes:

In includes/header.php, find:



Replace with:
<li><a href="teams.php">Teams</a></li>
<li><a href="schedules.php">Schedules</a></li>

In includes/application_top.php, find:
//if (!$mysqli) {

and replace with:
if (!$mysqli) {

Also find:
	}
//} else {
//	die('Database not connected.  Please check your config file for proper installation.');
//}

and replace with:
	} else {
	die('Database not connected.  Please check your config file for proper installation.');
	}
}

After:
$adminUser = $login->get_user('admin');

Add:
if($user->userID == $adminUser->userID) {
$user->is_admin = 1;
} else {
$user->is_admin = 0;
}

**Comment by rothkj1022** [comment]
Thank you for your bug reports.  I had failed to check in the updated database structure and some other minor updates, which have been checked in now.  Enjoy.
